# 사이트 설정
site_name: BZepeto — User Guide
site_url: https://mayalhc.github.io/bzepeto/
site_author: chamiseul

# 테마 설정
theme:
  name: readthedocs
  highlightjs: true
  collapse_navigation: false # 전체를 항상 펼침
  sticky_navigation: true
  navigation_depth: 4
  titles_only: false

extra_css:
  - custom.css

# 네비게이션 (메뉴 구조)
nav:
  - BZepeto Guide:
    - "Welcome to BZepeto": index.md # 상위 메뉴 클릭 시 바로 보일 파일
    - "All add-ons & guides": https://mayalhc.github.io/GroomForge-Wiki/

# 마크다운 확장 기능 (기능 강화)
markdown_extensions:
  - admonition # 노션의 '콜아웃'처럼 경고/정보 박스 생성
  - tables # 표 지원
  - pymdownx.details
  - pymdownx.superfences

# 플러그인 설정
hooks:
  - hooks/media.py

plugins:
  - search # 검색창 기능
